services:
  php-server:
    image: ghcr.io/badmintoncore/app-php-server:latest
    restart: unless-stopped
    platform: linux/amd64
    environment:
      SERVER_NAME: localhost, php:80
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
      - "9003:9003"
  db:
    image: mariadb:latest
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vestis
      MYSQL_USER: vestis
      MYSQL_PASSWORD: vestis
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: