INSERT INTO category (name, parentCategoryId)
VALUES ('Kleidung', NULL),
       ('Accessoires', NULL),
       ('Shirts', 1),
       ('Sweater', 1),
       ('Taschen', 2),
       ('Caps', 2);

INSERT INTO size (size)
VALUES ('S'),
       ('M'),
       ('L'),
       ('XL'),
       ('XXL');

INSERT INTO color (hex, name)
VALUES ('008000', 'Grün'),
       ('0000FF', 'Blau'),
       ('000000', 'Schwarz'),
       ('FFFFFF', 'Weiß'),
       ('F5F5DC', 'Beige');

INSERT INTO productType (categoryId, name, material, price, imgPath, description, collection, careInstructions,
                         origin, extraFields)
VALUES (3, 'Retro Sunburst Tee', '100% Bio-Baumwolle', 35, './images/retro_sunburst.jpg',
        'Weiches Retro-T-Shirt aus Bio-Baumwolle mit Sonnenmuster – perfekt für lässige Sommertage.',
        'Summer Retro 2025', 'Maschinenwäsche bei 30°C, auf links waschen, nicht in den Trockner geben.',
        'Made in Germany', JSON_OBJECT('fabric_weight', '180 g/m²', 'fit', 'Regular Fit')),
       (3, 'Cassette Vibes', '100% Baumwolle', 32, './images/cassette_vibes.jpg',
        'Hochwertiges Baumwollshirt im kultigen Kassetten-Design – für echte 80s-Fans.', 'Summer Retro 2025',
        'Maschinenwäsche bei 30°C, Feinwaschgang empfohlen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '190 g/m²', 'fit', 'Loose Fit')),
       (3, 'Pixel Palm Tee', '100% Baumwolle', 37, './images/pixel_palm.jpg',
        'Luftiges Retro-T-Shirt mit 8-Bit-Palmenmotiv – Sommer, Sonne, Nostalgie.', 'Summer Retro 2025',
        'Schonwaschgang bei 30°C, auf links waschen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '175 g/m²', 'fit', 'Regular Fit')),
       (3, 'VHS Club Shirt', '100% Bio-Baumwolle', 34, './images/vhs_club.jpg',
        'Oversized Fit im VHS-Design – perfekt für entspannte Vintage-Looks.', 'Summer Retro 2025',
        'Maschinenwäsche kalt, auf links bügeln.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '200 g/m²', 'fit', 'Oversized Fit')),
       (3, 'Neon Nights Tee', '100% Baumwolle', 37, './images/neon_nights.jpg',
        'Retro-Discofeeling in sanften Farben – dein Essential für laue Sommernächte.', 'Summer Retro 2025',
        'Maschinenwäsche bei 30°C, geringe Schleuderzahl empfohlen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '175 g/m²', 'fit', 'Relaxed Fit')),
       (3, 'Analog Mood', '100% Baumwolle', 35, './images/analog_mood.jpg',
        'Schlicht und stilvoll – inspiriert vom Charme alter Polaroids.', 'Summer Retro 2025',
        'Maschinenwäsche bei 30°C, nicht im Trockner trocknen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '185 g/m²', 'fit', 'Regular Fit')),
       (3, 'Sunset Radio', '100% Bio-Baumwolle', 39, './images/sunset_radio.jpg',
        'Vintage-Radiodesign trifft weichen Baumwollstoff – perfekt zum Chillen.', 'Summer Retro 2025',
        'Feinwäsche bei 30°C, sanft schleudern.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '190 g/m²', 'fit', 'Regular Fit')),
       (3, 'Lo-Fi Coastline', '100% Baumwolle', 34, './images/lofi_coastline.jpg',
        'Lässiges Shirt mit Lo-Fi Coastline Print – entspannt, stilvoll, retro.', 'Summer Retro 2025',
        'Maschinenwäsche bei 30°C, auf links drehen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '170 g/m²', 'fit', 'Relaxed Fit')),
       (3, 'Synthwave Dreams', '100% Bio-Baumwolle', 39, './images/synthwave_dreams.jpg',
        'Modernes Slim Fit Shirt mit Synthwave-Farben im Retro-Style.', 'Summer Retro 2025',
        'Kaltwäsche empfohlen, nicht bleichen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '180 g/m²', 'fit', 'Slim Fit')),
       (3, 'Tape Deck Soul', '100% Baumwolle', 36, './images/tape_deck_soul.jpg',
        'Mixtape-Nostalgie zum Anziehen – lässiges Retro-Tee für echte Musikfans.', 'Summer Retro 2025',
        'Maschinenwäsche bei 30°C, nicht im Trockner trocknen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '185 g/m²', 'fit', 'Regular Fit'));

INSERT INTO productType (categoryId, name, material, price, imgPath, description, collection, careInstructions,
                         origin, extraFields)
VALUES (4, 'Sunset Fade Crew', '85% Bio-Baumwolle, 15% recyceltes Polyester', 65, './images/sunset_fade.jpg',
        'Weicher Crewneck mit sanftem Farbverlauf – wie ein Sonnenuntergang in Stoffform.', 'Retro Layers 2025',
        'Maschinenwäsche bei 30°C, auf links waschen, nicht bügeln.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '300 g/m²', 'fit', 'Relaxed Fit')),
       (4, 'Analog Waves Sweater', '100% Bio-Baumwolle', 69, './images/analog_waves.jpg',
        'Wellenprint im Stil alter Audioanzeigen – stylisch und warm zugleich.', 'Retro Layers 2025',
        'Maschinenwäsche bei 30°C, Feinwaschgang empfohlen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '290 g/m²', 'fit', 'Oversized Fit')),
       (4, 'Lo-Fi Sunset Pullover', '80% Baumwolle, 20% recyceltes Polyester', 67, './images/lofi_sunset.jpg',
        'Sweater mit Lo-Fi-Print – fühlt sich an wie ein Abend auf Kassette.', 'Retro Layers 2025',
        'Maschinenwäsche bei 30°C, auf links drehen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', 'r g/m²', 'fit', 'Regular Fit')),
       (4, 'Rewind Club', '100% Bio-Baumwolle', 72, './images/rewind_club.jpg',
        'Statement-Sweater mit REWIND-Print – für echte Vintage-Enthusiasten.', 'Retro Layers 2025',
        'Maschinenwäsche kalt, nicht im Trockner trocknen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '320 g/m²', 'fit', 'Oversized Fit')),
       (4, 'Polaroid Echo', '100% Baumwolle', 68, './images/polaroid_echo.jpg',
        'Ein Sweater wie ein altes Foto – mit typischem Farbverlauf und Retro-Flair.', 'Retro Layers 2025',
        'Schonwaschgang bei 30°C, auf links waschen.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '300 g/m²', 'fit', 'Relaxed Fit')),
       (4, 'Static Memories', '85% Baumwolle, 15% recyceltes Polyester', 63, './images/static_memories.jpg',
        'Leicht strukturierter Sweater im Stil eines alten TV-Rauschens.', 'Retro Layers 2025',
        'Feinwäsche bei 30°C, auf links bügeln.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '280 g/m²', 'fit', 'Regular Fit')),
       (4, 'Cassette Club Crew', '100% Bio-Baumwolle', 69, './images/cassette_crew.jpg',
        'Kassetten-Grafik auf kuscheligem Baumwollstoff – 90s in modernem Gewand.', 'Retro Layers 2025',
        'Maschinenwäsche bei 30°C, keine Bleichmittel verwenden.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '300 g/m²', 'fit', 'Loose Fit')),
       (4, 'Fade-In Pullover', '100% Baumwolle', 65, './images/fadein_pullover.jpg',
        'Minimalistischer Sweater mit subtilem Farbverlauf – clean und retro zugleich.', 'Retro Layers 2025',
        'Maschinenwäsche bei 30°C, kein Weichspüler.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '310 g/m²', 'fit', 'Regular Fit')),
       (4, 'Stereo Sunset', '80% Bio-Baumwolle, 20% recyceltes Polyester', 70, './images/stereo_sunset.jpg',
        'Oversized Sweater mit grafischem Sunset-Stick – retro und cozy.', 'Retro Layers 2025',
        'Maschinenwäsche kalt, auf links bügeln.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '25 g/m²', 'fit', 'Oversized Fit')),
       (4, 'Tracklist Vibes', '100% Bio-Baumwolle', 70, './images/tracklist_vibes.jpg',
        'Sweater mit aufgedruckter Tracklist – wie ein Mixtape für kalte Tage.', 'Retro Layers 2025',
        'Waschen bei 30°C, auf links drehen, nicht in den Trockner geben.', 'Made in Germany',
        JSON_OBJECT('fabric_weight', '300 g/m²', 'fit', 'Relaxed Fit'));

INSERT INTO productType (categoryId, name, material, price, imgPath, description, collection, careInstructions,
                         origin, extraFields)
VALUES (5, 'Metro Loop Bag', 'Gewachste Baumwolle', 59.90, './images/metro_loop.jpg',
        'Schlichte Umhängetasche im Metro-Design – wasserabweisend und stilvoll zugleich.', 'Urban Heritage 2025',
        'Mit feuchtem Tuch reinigen, nicht waschen.', 'Made in Germany',
        JSON_OBJECT('volume', '14 Liter', 'closure', 'Magnetverschluss', 'straps', 'Verstellbarer Schulterriemen',
                    'compartments', '1 Hauptfach, 1 Reißverschluss-Innenfach')),
       (5, 'Cassette Messenger', 'Recyceltes Polyester', 69.00, './images/cassette_messenger.jpg',
        'Messenger Bag im 90s Kassettenstil – urbaner Klassiker mit moderner Funktion.', 'Urban Heritage 2025',
        'Oberfläche mit feuchtem Tuch reinigen.', 'Made in Germany',
        JSON_OBJECT('volume', '16 Liter', 'closure', 'Klett und Schnalle', 'straps', 'Schulterriemen gepolstert',
                    'compartments', 'Laptopfach, Organizer, Frontfach')),
       (5, 'Lo-Fi Backpack', 'Canvas & veganes Leder', 79.00, './images/lofi_backpack.jpg',
        'Retro-Rucksack mit Lo-Fi Patch – robust und stylisch für unterwegs.', 'Urban Heritage 2025',
        'Nicht waschen, punktuell reinigen.', 'Made in Germany',
        JSON_OBJECT('volume', '18 Liter', 'closure', 'Kordelzug & Magnetklappe', 'straps', 'Verstellbare Canvas-Träger',
                    'compartments', 'Großes Hauptfach, Innenfach mit Reißverschluss')),
       (5, 'Polaroid Pocket Tote', '100% Baumwoll-Canvas', 39.90, './images/polaroid_tote.jpg',
        'Tote Bag mit Polaroid-Stickerei – leicht, geräumig, retro.', 'Urban Heritage 2025', 'Handwäsche empfohlen.',
        'Made in Germany',
        JSON_OBJECT('volume', '10 Liter', 'closure', 'Offen mit Innendruckknopf', 'straps', 'Tragehenkel',
                    'compartments', '1 Hauptfach, 2 Steckfächer innen')),
       (5, 'Tape Deck Sling', 'Recyceltes Nylon', 42.00, './images/tape_deck_sling.jpg',
        'Kompakte Sling Bag mit Tape-Design – ideal für unterwegs.', 'Urban Heritage 2025',
        'Feucht abwischen, nicht bügeln.', 'Made in Germany',
        JSON_OBJECT('volume', '6 Liter', 'closure', 'Reißverschluss', 'straps', 'Crossbody verstellbar', 'compartments',
                    'Hauptfach, Frontfach mit Reißverschluss')),
       (5, 'Analog Track Tote', 'Canvas & veganes Leder', 59.50, './images/analog_track.jpg',
        'Große Tote Bag im Analog-Stil – klassisch und vielseitig.', 'Urban Heritage 2025',
        'Nicht waschen, feucht reinigen.', 'Made in Germany',
        JSON_OBJECT('volume', '12 Liter', 'closure', 'Magnetverschluss', 'straps', 'Tragegriffe + Schultergurt',
                    'compartments', '1 Hauptfach, Laptopfach innen')),
       (5, 'Sunset Radio Pouch', 'Baumwoll-Canvas', 24.90, './images/sunset_pouch.jpg',
        'Kleine Pouch mit Radiodetail – perfekt für Essentials oder als Accessoire.', 'Urban Heritage 2025',
        'Handwäsche, nicht schleudern.', 'Made in Germany',
        JSON_OBJECT('volume', '2 Liter', 'closure', 'Reißverschluss', 'straps', 'Ohne – als Etui oder Clutch',
                    'compartments', '1 Innenfach')),
       (5, 'VHS Days Rucksack', 'Robustes Nylon & Baumwolle', 82.00, './images/vhs_days.jpg',
        'Großer Rucksack mit VHS-Grafik – viel Platz und viel Stil.', 'Urban Heritage 2025',
        'Nicht waschen, feucht reinigen.', 'Made in Germany',
        JSON_OBJECT('volume', '20 Liter', 'closure', 'Zweiwege-Reißverschluss', 'straps', 'Gepolsterte Schultergurte',
                    'compartments', 'Laptopfach, Organizer-Fach vorne')),
       (5, 'Neon Fade Crossbody', 'Recyceltes Nylon', 44.00, './images/neon_crossbody.jpg',
        'Funktionale Crossbody Bag mit leuchtendem Retro-Patch.', 'Urban Heritage 2025', 'Mit feuchtem Tuch abwischen.',
        'Made in Germany',
        JSON_OBJECT('volume', '5 Liter', 'closure', 'Zipper', 'straps', 'Verstellbarer Crossbody-Riemen',
                    'compartments', '2 Fächer mit Reißverschluss')),
       (5, 'Lo-Fi Club Rolltop', 'Canvas mit PU-Beschichtung', 89.00, './images/lofi_rolltop.jpg',
        'Rolltop-Backpack mit Retro-Details – für Alltag und Abenteuer.', 'Urban Heritage 2025',
        'Punktuell mit weichem Tuch reinigen.', 'Made in Germany',
        JSON_OBJECT('volume', '22 Liter (erweiterbar)', 'closure', 'Rolltop mit Gurtverschluss', 'straps',
                    'Gepolsterte, ergonomische Träger', 'compartments', 'Großes Hauptfach, gepolstertes Laptopfach'));


INSERT INTO productType (categoryId, name, material, price, imgPath, description, collection, careInstructions,
                         origin, extraFields)
VALUES (6, 'Waveform Classic Cap', '100% Baumwoll-Twill', 29.90, './images/waveform_classic.jpg',
        'Schlichte 90s-Cap mit hochwertiger Stickerei – understated und retro.', 'Headlines 2025',
        'Nur Handwäsche, nicht bleichen.', 'Made in Germany',
        JSON_OBJECT('visor', 'Gebogener Schirm', 'closure', 'Metallschnalle hinten', 'design',
                    'Ton-in-Ton Stickerei vorn', 'ventilation', 'Bestickte Ösen')),
       (6, 'VHS Snap Cap', 'Canvas & Mesh', 32.00, './images/vhs_snapcap.jpg',
        'Trucker Cap mit klassischem VHS-Patch – perfekt für sonnige Tage.', 'Headlines 2025',
        'Nur punktuell reinigen.', 'Made in Germany',
        JSON_OBJECT('visor', 'Flacher Schirm', 'closure', 'Snapback', 'design', 'Retro-Patch vorn, Mesh hinten',
                    'ventilation', 'Mesh-Rückseite')),
       (6, 'Cassette Curve', '100% Baumwolle', 31.50, './images/cassette_curve.jpg',
        'Lässige Cap mit ikonischem Kassettendesign – 80s-Vibes pur.', 'Headlines 2025', 'Handwäsche, nicht bügeln.',
        'Made in Germany', JSON_OBJECT('visor', 'Gebogener Schirm', 'closure', 'Klettverschluss', 'design',
                                       'Kassetten-Stickerei auf der Front', 'ventilation', 'Bestickte Luftösen')),
       (6, 'Analog Sun Visor', 'Canvas & Baumwolle', 27.90, './images/analog_visor.jpg',
        'Retro-Sonnenvisier für heiße Tage – leicht und stylisch.', 'Headlines 2025', 'Nur Handwäsche.',
        'Made in Germany', JSON_OBJECT('visor', 'Gebogener Schirm', 'closure', 'Klettverschluss', 'design',
                                       'Minimalistisches Logo-Stick vorne', 'ventilation', 'Offen (Visor-Stil)')),
       (6, 'Lo-Fi Script Cap', 'Cord', 34.00, './images/lofi_script.jpg',
        'Cord-Cap im 90s-Look mit edler Lo-Fi Stickerei.', 'Headlines 2025', 'Nicht waschen, punktuell reinigen.',
        'Made in Germany', JSON_OBJECT('visor', 'Flacher Schirm', 'closure', 'Metallschnalle', 'design',
                                       'Lo-Fi-Stickerei mit Retro-Schriftzug', 'ventilation', 'Gestickte Ösen')),
       (6, 'Neon Fade Snap', 'Recycelter Baumwoll-Mix', 30.00, './images/neon_fade_snap.jpg',
        'Cap mit Neon-Touch – zurückhaltend aber nicht langweilig.', 'Headlines 2025', 'Feucht abwischen.',
        'Made in Germany',
        JSON_OBJECT('visor', 'Gebogener Schirm', 'closure', 'Snapback', 'design', 'Kleines Neon-Detail an der Seite',
                    'ventilation', 'Mesh hinten')),
       (6, 'Sunset Patch Cap', 'Canvas', 33.50, './images/sunset_patch.jpg',
        'Capsule-Feeling in Cap-Form – für Retro-Sommer-Abende.', 'Headlines 2025', 'Handwäsche, lufttrocknen.',
        'Made in Germany',
        JSON_OBJECT('visor', 'Gebogener Schirm', 'closure', 'Metallschnalle', 'design', 'Sonnenuntergangs-Patch vorne',
                    'ventilation', 'Ösen')),
       (6, 'Pixel Palm Trucker', 'Polyester-Mesh & Baumwoll-Front', 32.90, './images/pixel_palm_trucker.jpg',
        'Trucker Cap mit digitaler Retro-Palme – ikonisch und luftig.', 'Headlines 2025',
        'Nicht in der Maschine waschen.', 'Made in Germany',
        JSON_OBJECT('visor', 'Flach', 'closure', 'Snapback', 'design', '8-Bit Palmen Stickerei', 'ventilation',
                    'Voll-Mesh Rückseite')),
       (6, 'Tape Deck Dad Hat', '100% Baumwoll-Twill', 29.00, './images/tape_dad_hat.jpg',
        'Zeitlose Dad Hat mit subtilem Tape-Stitch – einfach tragbar.', 'Headlines 2025',
        'Feucht abwischen, nicht bleichen.', 'Made in Germany',
        JSON_OBJECT('visor', 'Gebogen', 'closure', 'Metallschnalle', 'design', 'Minimalistisches Tape-Stitch vorn',
                    'ventilation', 'Gestickte Ösen')),
       (6, 'Clubhouse Cord Cap', 'Breitcord', 35.50, './images/clubhouse_cord.jpg',
        'Exklusive Cord-Cap mit dezentem Branding – retro pur.', 'Headlines 2025',
        'Nicht waschen, mit weichem Tuch reinigen.', 'Made in Germany',
        JSON_OBJECT('visor', 'Flacher Schirm', 'closure', 'Versteckte Klettleiste', 'design', 'Sticklogo „vestis.“',
                    'ventilation', 'Keine Ösen (klassischer Look)'));

INSERT INTO product (productTypeId, sizeId, colorId)
VALUES (1, 2, 1),
       (1, 2, 1),
       (1, 2, 1),
       (1, 2, 1),
       (1, 2, 1),
       (1, 3, 2),
       (1, 3, 2),
       (1, 3, 2),
       (1, 3, 2),
       (1, 3, 2),
       (1, 3, 2),
       (1, 3, 2),
       (1, 4, 3),
       (1, 4, 3),
       (1, 4, 3),
       (1, 4, 3),
       (1, 1, 1),
       (1, 1, 1),
       (1, 5, 4);

INSERT INTO product (productTypeId, sizeId, colorId)
VALUES (9, 2, 2),
       (9, 2, 2),
       (9, 2, 2),
       (9, 2, 2),
       (9, 2, 2),
       (9, 3, 1),
       (9, 3, 1),
       (9, 3, 1),
       (9, 3, 1),
       (9, 4, 3),
       (9, 4, 3),
       (9, 4, 3),
       (9, 5, 5),
       (9, 5, 5);

INSERT INTO product (productTypeId, sizeId, colorId)
VALUES (11, 2, 1),
       (11, 2, 1),
       (11, 2, 1),
       (11, 2, 1),
       (11, 3, 2),
       (11, 3, 2),
       (11, 3, 2),
       (11, 3, 2),
       (11, 3, 2),
       (11, 4, 3),
       (11, 4, 3),
       (11, 5, 4),
       (11, 1, 5);

INSERT INTO product (productTypeId, sizeId, colorId)
VALUES (21, 2, 3),
       (21, 2, 3),
       (21, 2, 3),
       (21, 2, 3),
       (21, 2, 3),
       (21, 2, 3),
       (21, 2, 5),
       (21, 2, 5),
       (21, 2, 5),
       (21, 2, 5);

INSERT INTO product (productTypeId, sizeId, colorId)
VALUES (31, 3, 2),
       (31, 3, 2),
       (31, 3, 2),
       (31, 3, 2),
       (31, 3, 2),
       (31, 3, 4),
       (31, 3, 4),
       (31, 3, 4);

INSERT INTO allowedColor (productTypeId, colorId)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (2, 1),
       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (3, 1),
       (3, 2),
       (3, 3),
       (3, 4),
       (3, 5),
       (4, 1),
       (4, 2),
       (4, 3),
       (4, 4),
       (4, 5),
       (5, 1),
       (5, 2),
       (5, 3),
       (5, 4),
       (5, 5),
       (6, 1),
       (6, 2),
       (6, 3),
       (6, 4),
       (6, 5),
       (7, 1),
       (7, 2),
       (7, 3),
       (7, 4),
       (7, 5),
       (8, 1),
       (8, 2),
       (8, 3),
       (8, 4),
       (8, 5),
       (9, 1),
       (9, 2),
       (9, 3),
       (9, 4),
       (9, 5),
       (10, 1),
       (10, 2),
       (10, 3),
       (10, 4),
       (10, 5),
       (11, 1),
       (11, 2),
       (11, 3),
       (11, 4),
       (11, 5),
       (12, 1),
       (12, 2),
       (12, 3),
       (12, 4),
       (12, 5),
       (13, 1),
       (13, 2),
       (13, 3),
       (13, 4),
       (13, 5),
       (14, 1),
       (14, 2),
       (14, 3),
       (14, 4),
       (14, 5),
       (15, 1),
       (15, 2),
       (15, 3),
       (15, 4),
       (15, 5),
       (16, 1),
       (16, 2),
       (16, 3),
       (16, 4),
       (16, 5),
       (17, 1),
       (17, 2),
       (17, 3),
       (17, 4),
       (17, 5),
       (18, 1),
       (18, 2),
       (18, 3),
       (18, 4),
       (18, 5),
       (19, 1),
       (19, 2),
       (19, 3),
       (19, 4),
       (19, 5),
       (20, 1),
       (20, 2),
       (20, 3),
       (20, 4),
       (20, 5),
       (21, 1),
       (21, 2),
       (21, 3),
       (21, 4),
       (21, 5),
       (22, 1),
       (22, 2),
       (22, 3),
       (22, 4),
       (22, 5),
       (23, 1),
       (23, 2),
       (23, 3),
       (23, 4),
       (23, 5),
       (24, 1),
       (24, 2),
       (24, 3),
       (24, 4),
       (24, 5),
       (25, 1),
       (25, 2),
       (25, 3),
       (25, 4),
       (25, 5),
       (26, 1),
       (26, 2),
       (26, 3),
       (26, 4),
       (26, 5),
       (27, 1),
       (27, 2),
       (27, 3),
       (27, 4),
       (27, 5),
       (28, 1),
       (28, 2),
       (28, 3),
       (28, 4),
       (28, 5),
       (29, 1),
       (29, 2),
       (29, 3),
       (29, 4),
       (29, 5),
       (30, 1),
       (30, 2),
       (30, 3),
       (30, 4),
       (30, 5),
       (31, 1),
       (31, 2),
       (31, 3),
       (31, 4),
       (31, 5),
       (32, 1),
       (32, 2),
       (32, 3),
       (32, 4),
       (32, 5),
       (33, 1),
       (33, 2),
       (33, 3),
       (33, 4),
       (33, 5),
       (34, 1),
       (34, 2),
       (34, 3),
       (34, 4),
       (34, 5),
       (35, 1),
       (35, 2),
       (35, 3),
       (35, 4),
       (35, 5),
       (36, 1),
       (36, 2),
       (36, 3),
       (36, 4),
       (36, 5),
       (37, 1),
       (37, 2),
       (37, 3),
       (37, 4),
       (37, 5),
       (38, 1),
       (38, 2),
       (38, 3),
       (38, 4),
       (38, 5),
       (39, 1),
       (39, 2),
       (39, 3),
       (39, 4),
       (39, 5),
       (40, 1),
       (40, 2),
       (40, 3),
       (40, 4),
       (40, 5);

INSERT INTO allowedSize (productTypeId, sizeId)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (2, 1),
       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (3, 1),
       (3, 2),
       (3, 3),
       (3, 4),
       (3, 5),
       (4, 1),
       (4, 2),
       (4, 3),
       (4, 4),
       (4, 5),
       (5, 1),
       (5, 2),
       (5, 3),
       (5, 4),
       (5, 5),
       (6, 1),
       (6, 2),
       (6, 3),
       (6, 4),
       (6, 5),
       (7, 1),
       (7, 2),
       (7, 3),
       (7, 4),
       (7, 5),
       (8, 1),
       (8, 2),
       (8, 3),
       (8, 4),
       (8, 5),
       (9, 1),
       (9, 2),
       (9, 3),
       (9, 4),
       (9, 5),
       (10, 1),
       (10, 2),
       (10, 3),
       (10, 4),
       (10, 5),
       (11, 1),
       (11, 2),
       (11, 3),
       (11, 4),
       (11, 5),
       (12, 1),
       (12, 2),
       (12, 3),
       (12, 4),
       (12, 5),
       (13, 1),
       (13, 2),
       (13, 3),
       (13, 4),
       (13, 5),
       (14, 1),
       (14, 2),
       (14, 3),
       (14, 4),
       (14, 5),
       (15, 1),
       (15, 2),
       (15, 3),
       (15, 4),
       (15, 5),
       (16, 1),
       (16, 2),
       (16, 3),
       (16, 4),
       (16, 5),
       (17, 1),
       (17, 2),
       (17, 3),
       (17, 4),
       (17, 5),
       (18, 1),
       (18, 2),
       (18, 3),
       (18, 4),
       (18, 5),
       (19, 1),
       (19, 2),
       (19, 3),
       (19, 4),
       (19, 5),
       (20, 1),
       (20, 2),
       (20, 3),
       (20, 4),
       (20, 5),
       (21, 1),
       (21, 2),
       (21, 3),
       (21, 4),
       (21, 5),
       (22, 1),
       (22, 2),
       (22, 3),
       (22, 4),
       (22, 5),
       (23, 1),
       (23, 2),
       (23, 3),
       (23, 4),
       (23, 5),
       (24, 1),
       (24, 2),
       (24, 3),
       (24, 4),
       (24, 5),
       (25, 1),
       (25, 2),
       (25, 3),
       (25, 4),
       (25, 5),
       (26, 1),
       (26, 2),
       (26, 3),
       (26, 4),
       (26, 5),
       (27, 1),
       (27, 2),
       (27, 3),
       (27, 4),
       (27, 5),
       (28, 1),
       (28, 2),
       (28, 3),
       (28, 4),
       (28, 5),
       (29, 1),
       (29, 2),
       (29, 3),
       (29, 4),
       (29, 5),
       (30, 1),
       (30, 2),
       (30, 3),
       (30, 4),
       (30, 5),
       (31, 1),
       (31, 2),
       (31, 3),
       (31, 4),
       (31, 5),
       (32, 1),
       (32, 2),
       (32, 3),
       (32, 4),
       (32, 5),
       (33, 1),
       (33, 2),
       (33, 3),
       (33, 4),
       (33, 5),
       (34, 1),
       (34, 2),
       (34, 3),
       (34, 4),
       (34, 5),
       (35, 1),
       (35, 2),
       (35, 3),
       (35, 4),
       (35, 5),
       (36, 1),
       (36, 2),
       (36, 3),
       (36, 4),
       (36, 5),
       (37, 1),
       (37, 2),
       (37, 3),
       (37, 4),
       (37, 5),
       (38, 1),
       (38, 2),
       (38, 3),
       (38, 4),
       (38, 5),
       (39, 1),
       (39, 2),
       (39, 3),
       (39, 4),
       (39, 5),
       (40, 1),
       (40, 2),
       (40, 3),
       (40, 4),
       (40, 5);