name: Pull Request Testing

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.php'  # Optional: you can restrict to certain files, such as PHP files

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' # Change to the version of PHP you're using
          extensions: mbstring, mysqli, curl # Add any PHP extensions you need
          coverage: xdebug # Enable Xdebug if you want coverage reports

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --optimize-autoloader

      - name: Run PhpCsFixer
        run: PHP_CS_FIXER_IGNORE_ENV=true vendor/bin/php-cs-fixer fix . --dry-run --verbose

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse .

